# Generated by Django 4.1 on 2023-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
    ]
