# Generated by Django 4.1 on 2023-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_requestlog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
